### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by xeruf** [coquelicot/mpris-youtube#1]
Could you add installation instructions to the README? Does this still work?

**Comment by coquelicot** [comment]
Hi,

you may check `install.sh` for installation guide.

I think it's not working now as it depends on GNOME 3's undocumented API at that time, which is likely deprecated or even removed.

Update:
To be clear, the GUI this project intent to work with should not work now, however, the CLI part should work as long as package like youtube-dl still works in the same way.

**Comment by coquelicot** [comment]
No update for more than 1 year. I'll just close this issue.

**Comment by xeruf** [comment]
I had probably missed this ^^ but it seems that it is written for GNOME, and I am using KDE now, which has the Plasma Integration that makes Youtube work with MPRIS. Although, it doesn't allow skipping in Playlists - is your extension capable of that?
